language: cpp
compiler: gcc
env:
 - TRAVIS_CVC4_PACKAGE=rpm
 - TRAVIS_CVC4_PACKAGE=debian
before_install:
# dhart/ppa is for cxxtest package, which doesn't appear officially until quantal
 - travis_retry sudo apt-add-repository -y ppa:dhart/ppa
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq libgmp-dev antlr3 libantlr3c-dev libboost-dev libboost-thread-dev swig2.0 libcln-dev cxxtest openjdk-7-jdk rpm devscripts
 - travis_retry git clone git://github.com/CVC4/CVC4.git cvc4
before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
 - export PATH=$PATH:$JAVA_HOME/bin
 - export JAVA_CPPFLAGS=-I$JAVA_HOME/include
script: |
   normal="$(echo -e '\033[0m')" red="$normal$(echo -e '\033[01;31m')" green="$normal$(echo -e '\033[01;32m')"
   DATE=`date +"%Y-%m-%d"`;
   rpmvers=`echo $DATE | tr - _`;
   rpmdate=`date '+%a %b %d %Y'`;
   (cd cvc4 && ./autogen.sh && ./configure && make dist) &&
   case "$TRAVIS_CVC4_PACKAGE" in
   rpm)
     mkdir rpmbuild &&
     cd rpmbuild &&
     echo "%_topdir `pwd`" > "$HOME/.rpmmacros" &&
     echo "%_smt_mflags -j2" >> "$HOME/.rpmmacros" &&
     mkdir -p SPECS SOURCES &&
     cp ../rpm/cvc4-nightly.spec SPECS &&
     cp ../rpm/cvc4-rpm.patch SOURCES &&
     cp ../cvc4/builds/cvc4*tar.gz SOURCES/cvc4-$DATE.tar.gz &&
     perl -pi -e 's,^(Version: *).*,${1}'$rpmvers',;s,^(Source:.*/cvc4-)[0-9-]*(\.tar\.gz)$,${1}'$DATE'$2,;s,^(%setup -q -n cvc4-)[0-9-]*$,${1}'$DATE',;s,^%changelog$,%changelog\\n* '"$rpmdate"' Morgan Deters <mdeters\@cs.nyu.edu> '$DATE'-1\\n- Automated Travis-CI build of CVC4.,' SPECS/cvc4-nightly.spec &&
     rpmbuild -ba SPECS/cvc4-nightly.spec &&
     echo && echo "${green}RPM BUILD PASSED${normal}" && echo
     ;;
   debian)
     mkdir debwork &&
     cd debwork &&
     cp ../cvc4/builds/cvc4*tar.gz cvc4_$DEBVERSION.orig.tar.gz &&
     tar xfz cvc4_$DEBVERSION.orig.tar.gz &&
     mv cvc4-* cvc4-$DEBVERSION &&
     cd cvc4-$DEBVERSION &&
     cp -a ../../debian debian &&
     cat > changelog.tmp <<EOF &&
   cvc4 ($DEBVERSION-1) unstable; urgency=low
   
     * Automated Travis-CI build of Debian package from master sources.
   
    -- Morgan Deters <mdeters@cs.nyu.edu>  `date -R`
   EOF
     cat debian/changelog >> changelog.tmp &&
     mv -v changelog.tmp debian/changelog &&
     debuild -j2 -us -uc &&
     echo && echo "${green}DEBIAN BUILD PASSED${normal}" && echo
     exit 1
     ;;
   *)
     echo && echo "${red}ERROR: unknown package to build: \"$TRAVIS_CVC4_PACKAGE\"${normal}" && echo;
     exit 1
     ;;
   esac
matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_CVC4_PACKAGE=debian
notifications:
  email:
    recipients: mdeters@cs.nyu.edu
    on_success: change
    on_failure: always
